spring:
  application:
    name: spring-boot-2-db
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  flyway:
    enabled: false

db1:
  driver-class-name: org.h2.Driver
  jdbc-url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
  username: sa
  password: password
  hikari:
    pool-name: HikariPool-DB1
db2:
  driver-class-name: org.h2.Driver
  jdbc-url: jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1
  username: sa
  password: password
  hikari:
    pool-name: HikariPool-DB2

